// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profile} from '../models';

export function GetProfiles(arg1:string):Promise<profile.ProfileList>;
