// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProfiles(arg1) {
  return window['go']['profile']['ProfileRunT']['GetProfiles'](arg1);
}
