// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitWebSocket() {
  return window['go']['websocket']['WebSocketManager']['InitWebSocket']();
}

export function ShutdownServer() {
  return window['go']['websocket']['WebSocketManager']['ShutdownServer']();
}

export function StartServer() {
  return window['go']['websocket']['WebSocketManager']['StartServer']();
}
