// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitWebSocket():Promise<void>;

export function ShutdownServer():Promise<void>;

export function StartServer():Promise<void>;
