// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfigVariable(arg1:string):Promise<string>;

export function GetRuntimeConfig():Promise<config.Config>;

export function SetConfigVariable(arg1:string,arg2:string):Promise<void>;
