// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigVariable(arg1) {
  return window['go']['config']['ConfigRunT']['GetConfigVariable'](arg1);
}

export function GetRuntimeConfig() {
  return window['go']['config']['ConfigRunT']['GetRuntimeConfig']();
}

export function SetConfigVariable(arg1, arg2) {
  return window['go']['config']['ConfigRunT']['SetConfigVariable'](arg1, arg2);
}
