// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {os} from '../models';
import {context} from '../models';

export function StartServer(arg1:string):Promise<os.Process>;

export function Startup(arg1:context.Context):Promise<void>;
