// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['launcher']['App']['Close']();
}

export function CloseServers() {
  return window['go']['launcher']['App']['CloseServers']();
}

export function Hide() {
  return window['go']['launcher']['App']['Hide']();
}

export function Minimize() {
  return window['go']['launcher']['App']['Minimize']();
}

export function Show() {
  return window['go']['launcher']['App']['Show']();
}

export function Startup(arg1) {
  return window['go']['launcher']['App']['Startup'](arg1);
}
