// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function CloseServers():Promise<void>;

export function Hide():Promise<void>;

export function Minimize():Promise<void>;

export function Show():Promise<void>;
