// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';

export function CreateConfigIfNotExist(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetConfig():Promise<launcher.Config>;

export function GetConfigByModID(arg1:string):Promise<launcher.Config>;

export function GetConfigByModName(arg1:string):Promise<launcher.Config>;

export function UpdateConfig(arg1:launcher.Config):Promise<void>;
