// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConfigIfNotExist(arg1, arg2, arg3, arg4) {
  return window['go']['launcher']['Config']['CreateConfigIfNotExist'](arg1, arg2, arg3, arg4);
}

export function GetConfig() {
  return window['go']['launcher']['Config']['GetConfig']();
}

export function GetConfigByModID(arg1) {
  return window['go']['launcher']['Config']['GetConfigByModID'](arg1);
}

export function GetConfigByModName(arg1) {
  return window['go']['launcher']['Config']['GetConfigByModName'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['launcher']['Config']['UpdateConfig'](arg1);
}
