// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {launcher} from '../models';
import {websocket} from '../models';

export function DequeueDownload():Promise<launcher.DownloadRequest>;

export function EnqueueDownload(arg1:number,arg2:string,arg3:websocket.Conn,arg4:string,arg5:string):Promise<void>;

export function Mod(arg1:number,arg2:string,arg3:websocket.Conn,arg4:string,arg5:string):Promise<void>;

export function StartDownloading():Promise<void>;
