// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DequeueDownload() {
  return window['go']['launcher']['Download']['DequeueDownload']();
}

export function EnqueueDownload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['launcher']['Download']['EnqueueDownload'](arg1, arg2, arg3, arg4, arg5);
}

export function Mod(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['launcher']['Download']['Mod'](arg1, arg2, arg3, arg4, arg5);
}

export function StartDownloading() {
  return window['go']['launcher']['Download']['StartDownloading']();
}
