// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateMod():Promise<void>;

export function DisableMods():Promise<void>;

export function ProfileThrowMissing():Promise<void>;

export function ThrowConflict():Promise<void>;
