// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateMod() {
  return window['go']['launcher']['Mod']['ActivateMod']();
}

export function DisableMods() {
  return window['go']['launcher']['Mod']['DisableMods']();
}

export function ProfileThrowMissing() {
  return window['go']['launcher']['Mod']['ProfileThrowMissing']();
}

export function ThrowConflict() {
  return window['go']['launcher']['Mod']['ThrowConflict']();
}
