// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartServer() {
  return window['go']['launcher']['MTGA']['StartServer']();
}
