// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Check() {
  return window['go']['launcher']['Online']['Check']();
}

export function Heartbeat() {
  return window['go']['launcher']['Online']['Heartbeat']();
}
