// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModEntry(arg1:string):Promise<void>;

export function Check(arg1:number):Promise<boolean>;

export function Clear():Promise<void>;

export function ClearIconCache():Promise<void>;

export function ExtractArchive(arg1:string,arg2:string):Promise<void>;
