// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddModEntry(arg1) {
  return window['go']['launcher']['Storage']['AddModEntry'](arg1);
}

export function Check(arg1) {
  return window['go']['launcher']['Storage']['Check'](arg1);
}

export function Clear() {
  return window['go']['launcher']['Storage']['Clear']();
}

export function ClearIconCache() {
  return window['go']['launcher']['Storage']['ClearIconCache']();
}
