// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Error(arg1:string,arg2:string):Promise<void>;

export function Info():Promise<void>;

export function Panic(arg1:string,arg2:string):Promise<void>;

export function Reload():Promise<void>;

export function TestError(arg1:string,arg2:string,arg3:context.Context):Promise<void>;
