// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Error(arg1:string,arg2:string):Promise<void>;

export function Panic(arg1:string,arg2:string):Promise<void>;

export function Question(arg1:string,arg2:string):Promise<boolean>;

export function Reload():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
