// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Error(arg1, arg2) {
  return window['go']['launcher']['UI']['Error'](arg1, arg2);
}

export function Panic(arg1, arg2) {
  return window['go']['launcher']['UI']['Panic'](arg1, arg2);
}

export function Question(arg1, arg2) {
  return window['go']['launcher']['UI']['Question'](arg1, arg2);
}

export function Reload() {
  return window['go']['launcher']['UI']['Reload']();
}

export function Startup(arg1) {
  return window['go']['launcher']['UI']['Startup'](arg1);
}
