// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Error(arg1, arg2) {
  return window['go']['launcher']['UI']['Error'](arg1, arg2);
}

export function Info() {
  return window['go']['launcher']['UI']['Info']();
}

export function Panic(arg1, arg2) {
  return window['go']['launcher']['UI']['Panic'](arg1, arg2);
}

export function Reload() {
  return window['go']['launcher']['UI']['Reload']();
}

export function TestError(arg1, arg2, arg3) {
  return window['go']['launcher']['UI']['TestError'](arg1, arg2, arg3);
}
